# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  info_logger:
    class: Monolog\Logger
    arguments: [my_info]
    calls:
        - [pushHandler, [@info_log_handler]]

  info_log_handler:
    class: Monolog\Handler\StreamHandler
    arguments: [%kernel.root_dir%/logs/info.log, 100]

  error_logger:
    class: Monolog\Logger
    arguments: [my_info]
    calls:
        - [pushHandler, [@error_log_handler]]

  error_log_handler:
    class: Monolog\Handler\StreamHandler
    arguments: [%kernel.root_dir%/logs/error.log, 100]